
mixin OfGen {
  String generateHeader() {
    String function =
    """
    // GENERATED CODE - DO NOT MODIFY BY HAND
    // Generated by YukiAttanos style_generator 
    """;

    return function;
  }
}
