
mixin HeaderGen {
  String generateHeader() {
    String function =
    """
    // GENERATED CODE - DO NOT MODIFY BY HAND
    // 
    // * * * * * * * * * * * * * * *
    // Generated by style_generator 
    // * * * * * * * * * * * * * * *
    // 
    // coverage:ignore-file
    // ignore_for_file: type=lint
    """;

    return function;
  }
}
